<?php
require_once("Mage/Newsletter/controllers/SubscriberController.php");

class Activated_NewsletterCoupon_SubscriberController extends Mage_Newsletter_SubscriberController 
{
	public function newAction()
    { 
        if ($this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
            $session            = Mage::getSingleton('core/session');
            $customerSession    = Mage::getSingleton('customer/session');
            $email              = (string) $this->getRequest()->getPost('email');

           	// Coupon code generator
           	$ruleId				= Mage::getStoreConfig('newslettercoupon/view/rule');
           	$rule 				= Mage::getModel('salesrule/rule')->load($ruleId);
           	$coupon 			= Mage::getModel('salesrule/coupon');
            $enabled            = Mage::helper('newslettercoupon')->isEnabled();
            $ruleType           = $rule->getUseAutoGeneration();

            try {
                if (!Zend_Validate::is($email, 'EmailAddress')) {
                    Mage::throwException($this->__('Please enter a valid email address.'));
                }

                if (Mage::getStoreConfig(Mage_Newsletter_Model_Subscriber::XML_PATH_ALLOW_GUEST_SUBSCRIBE_FLAG) != 1 && 
                    !$customerSession->isLoggedIn()) {
                    Mage::throwException($this->__('Sorry, but administrator denied subscription for guests. Please <a href="%s">register</a>.', Mage::helper('customer')->getRegisterUrl()));
                }

                $ownerId = Mage::getModel('customer/customer')
                        ->setWebsiteId(Mage::app()->getStore()->getWebsiteId())
                        ->loadByEmail($email)
                        ->getId();
                if ($ownerId !== null && $ownerId != $customerSession->getId()) {
                    Mage::throwException($this->__('This email address is already assigned to another user.'));
                }

                // Generate and save coupon code
                if ($enabled) {
                    if ($ruleType == 1) {
                        $generator = $rule->getCouponCodeGenerator();
                        $coupon_code = $generator->generateCode();
                        $coupon->setId(null)
                        ->setRuleId($ruleId)
                        ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                        ->setCode($coupon_code)
                        ->save();

                        $coupon->save();
                    } else {
                        $coupon_code = $rule->getPrimaryCoupon()->getCode();
                    }
                }

                $status = Mage::getModel('newsletter/subscriber')->subscribe($email, $coupon_code);
                if ($status == Mage_Newsletter_Model_Subscriber::STATUS_NOT_ACTIVE) {
                    $session->addSuccess($this->__('Confirmation request has been sent.'));
                }
                else {
                    $session->addSuccess($this->__('Thank you for your subscription.'));
                }
            }
            catch (Mage_Core_Exception $e) {
                $session->addException($e, $this->__('There was a problem with the subscription: %s', $e->getMessage()));
            }
            catch (Exception $e) {
                $session->addException($e, $this->__('There was a problem with the subscription.'));
            }
        }
        $this->_redirectReferer();
    }
}
?>